var animals_array = [
    ["modal1", "DOLPHIN", "Eats<br>Mass<br>Scientific name<br>Conservation status<br>Length<br>Speed<br>Family", "Small Fish<br>70 – 150 kg (Adult)<br>Delphinus<br>Vulnerable<br>2 - 4 m (Adult)<br>60 km/h (Maximum, In Short Bursts)<br>Cetacean","A dolphin is an aquatic mammal within the infraorder<br>Cetacea. Dolphin species belong to the families<br>Delphinidae Platanistidae , Pontoporiidae, and the extinct<br>Lipotidae. There are 40 extant species named as dolphins.<br>Dolphins range in size from the 1.7-metre-long (5 ft 7 in)<br>and 50-kilogram (110-pound) Maui's dolphin to the 9.5 m<br>(31 ft 2 in) and 10-tonne (11-short-ton) orca.", "img/animal_01_03.png", "img/animal_01_04.png"],
    ["modal2", "GREAT WHITE SHARK", "Eats<br>Mass<br>Scientific name<br>Conservation status<br>Length<br>Speed<br>Family", "Earless seals<br>520 – 770 kg (Adult)<br>Carcharodon carcharias<br>Vulnerable<br>4 – 4.9 m (Adult)<br>56 km/h (Maximum, In Short Bursts)<br>Lamnidae","The great white shark (Carcharodon carcharias), also<br>known as the white shark, white pointer, or simply<br>great white, is a species of large mackerel shark which<br>can be found in the coastal surface waters of all<br>the major oceans. It is notable for its size, with larger<br>female individuals growing to 6.1 m (20 ft) in length and<br>1,905–2,268 kg (4,200–5,000 lb) in weight at maturity.", "img/animal_02_03.png", "img/animal_02_04.png"],
    ["modal3", "WHALE SHARK", "Eats<br>Mass<br>Scientific name<br>Conservation status<br>Length<br>Speed<br>Family", "Earless seals<br>19,000 kg (Adult)<br>Rhincodon typus<br>Not extinct<br>5.5 – 10 m (Adult)<br>5 km/h (Maximum, In Short Bursts)<br>Rhincodontidae","The whale shark (Rhincodon typus) is a slow-moving,<br>filter-feeding carpet shark and the largest known extant<br>fish species. The largest confirmed individual had <br>a length of 18.8 m (61.7 ft). The whale shark holds many<br>records for size in the animal kingdom, most notably<br>being by far the largest living nonmammalian vertebrate.<br>It is the sole member of the genus Rhincodon.", "img/animal_03_03.png", "img/animal_03_04.png"],
    ["modal4", "SEA TURTLE", "Eats<br>Mass<br>Scientific name<br>Conservation status<br>Length<br>Speed<br>Family", "crabs, shrimps<br>160 - 400 kg (Adult)<br>Chelonioidea<br>Not extinct<br>80 - 140 cm (Adult)<br>35 km/h (Maximum, In Short Bursts)<br>Reptilia","Sea turtles, sometimes called marine turtles, are reptiles<br>of the order Testudines and of the suborder Cryptodira.<br>The seven existing species of sea turtles are the flatback,<br>green, hawksbill, leatherback, loggerhead, Kemp's ridley,<br>and olive ridley sea turtles. All six of the sea turtle<br>species present in US waters  are listed as endangered<br>and/or threatened under the Endangered Species Act.", "img/animal_04_03.png", "img/animal_04_04.png"],
    ["modal5", "SEA LION", "Eats<br>Mass<br>Scientific name<br>Conservation status<br>Length<br>Speed<br>Family", "squid, crabs<br>100 - 300 kg (Adult)<br>Otariinae<br>Not extinct<br>2 - 2.4 m (Adult)<br>40 km/h (Maximum, In Short Bursts)<br>Eared seal","An eared seal or otariid is any member of the marine<br>mammal family Otariidae, one of three groupings of<br>pinnipeds. They comprise 15 extant species in seven<br>genera and are commonly known either as sea lions<br>or fur seals, distinct from true seals and the walrus.<br>Otariids are adapted to a semiaquatic lifestyle, feeding<br>in the water, but breeding and resting on land or ice.", "img/animal_05_03.png", "img/animal_05_04.png"],
    ["modal6", "KING PENGUIN", "Eats<br>Mass<br>Scientific name<br>Conservation status<br>Length<br>Speed<br>Family", "small fish<br>9.3 – 17 kg (Adult)<br>Aptenodytes patagonicus<br>Least Concern<br>85 – 95 cm (Adult)<br>12 km/h (Maximum, In Short Bursts)<br>Penguins","Penguins are a group of aquatic flightless birds. They<br>live almost exclusively in the Southern Hemisphere:<br>only one species. Highly adapted for life in the water,<br>penguins have countershaded dark and white plumage<br>and flippers for swimming. Most penguins feed on krill,<br>fish, squid and other forms of sea life which they catch<br>with their bills and swallow it whole while swimming.", "img/animal_06_03.png", "img/animal_06_04.png"]
];

var special_array = [
    ["modal01", "img/art_01_1.jpg"],
    ["modal02", "img/art_02_1.jpg"],
    ["modal03", "img/art_03_1.jpg"],
    ["modal04", "img/art_04_1.jpg"],
    ["modal05", "img/art_05_1.jpg"],
    ["modal06", "img/art_06_1.jpg"],
];